# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-12 21:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Camera',
            fields=[
                ('idcamera', models.AutoField(db_column='idCamera', primary_key=True, serialize=False)),
                ('location', models.CharField(blank=True, db_column='Location', max_length=45, null=True)),
            ],
            options={
                'db_table': 'Camera',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Lightcontrol',
            fields=[
                ('idlightcontrol', models.AutoField(db_column='idLightControl', primary_key=True, serialize=False)),
                ('starttimestamp', models.DateTimeField(blank=True, db_column='StartTimestamp', null=True)),
                ('endtimestamp', models.DateTimeField(blank=True, db_column='EndTimestamp', null=True)),
                ('uuid', models.CharField(blank=True, db_column='UUID', max_length=45, null=True)),
            ],
            options={
                'db_table': 'LightControl',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Movement',
            fields=[
                ('idmovement', models.AutoField(db_column='idMovement', primary_key=True, serialize=False)),
                ('starttimestamp', models.DateTimeField(blank=True, db_column='StartTimestamp', null=True)),
                ('endtimestamp', models.DateTimeField(blank=True, db_column='EndTimestamp', null=True)),
                ('detector', models.CharField(blank=True, db_column='Detector', max_length=45, null=True)),
                ('uuid', models.CharField(blank=True, db_column='UUID', max_length=128, null=True)),
            ],
            options={
                'db_table': 'Movement',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('idpicture', models.AutoField(db_column='idPicture', primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(blank=True, db_column='Timestamp', null=True)),
                ('filelocation', models.CharField(blank=True, db_column='FileLocation', max_length=128, null=True)),
                ('filesize', models.IntegerField(blank=True, db_column='FileSize', null=True)),
                ('uploadtime', models.CharField(blank=True, db_column='UploadTime', max_length=45, null=True)),
            ],
            options={
                'db_table': 'Picture',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Picturemovement',
            fields=[
                ('idpicturemovement', models.AutoField(db_column='idPictureMovement', primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(blank=True, db_column='Timestamp', null=True)),
                ('filelocation', models.CharField(blank=True, db_column='FileLocation', max_length=128, null=True)),
                ('filesize', models.IntegerField(blank=True, db_column='FileSize', null=True)),
                ('uuid', models.CharField(blank=True, db_column='UUID', max_length=128, null=True)),
                ('uploadtime', models.CharField(blank=True, db_column='UploadTime', max_length=45, null=True)),
            ],
            options={
                'db_table': 'PictureMovement',
                'managed': False,
            },
        ),
    ]
